### ISSUE TITLE
Map packer just does not work

### ISSUE THREAD

**Issue by TheAndromedaCat** [Eagle-One-Development/Asset-Packer#3]
[I have a video here showing that the map packer just doesn't work for me.](https://www.youtube.com/watch?v=DO41gQvRc7A)

**Comment by DoctorGurke** [comment]
Have you tried it while *not* actively compiling a map?

**Comment by JustAssassinExists** [comment]
Yes, even while s&box is fully closed it still wont open at all

**Comment by DoctorGurke** [comment]
Unless you can give me an error or way to reproduce this properly, there's not much I can do right now, I'm afraid. The application runs fine on my local machine and on a test laptop that never had dotnet installed (after installing it through the windows prompt)

**Comment by DoctorGurke** [comment]
you can try launching it via cmd to see if dotnet throws an error perhaps

**Comment by JustAssassinExists** [comment]
> you can try launching it via cmd to see if dotnet throws an error perhaps

![image](https://user-images.githubusercontent.com/75682159/129621056-0c860fde-ac89-4b11-bbdb-188ef36f22dc.png)
Sadly not....

**Comment by DoctorGurke** [comment]
one last idea I'd have is to just run it as admin. Might be some trash AV silently preventing you from launching unsigned exes lol

**Comment by JustAssassinExists** [comment]
> one last idea I'd have is to just run it as admin. Might be some trash AV silently preventing you from launching unsigned exes lol

That doesn't work either... I'll just have to pack my assets manually. Its alright though! this was a weird experience i wasn't expecting
